const { Router } = require('express');
const { endpoint } = require('../utils/endpoint');


module.exports = (query) => {
   const router = Router();
   router.use('/footer', require('./footer')(query));
   router.use('/industries', require('./industries')(query));
   router.use('/tonics-hero', require('./tonicsHero')(query));
   router.use('/hero', require('./hero')(query));
   router.use('/ingredients', require('./ingredients')(query));
   router.use('/catalog', require('./catalog')(query));
   router.use('/tonics-seo-text-full', require('./tonicsSeoTextFull')(query));
   router.use('/about', require('./about')(query));
   router.use('/navigation', require('./navigation')(query));
   router.use('/partners', require('./partners')(query));
   router.use('/form', require('./form')(query));
   router.use('/blog', require('./blog')(query));
   router.use('/seo', require('./seo')(query));
  router.use('/seoHome', require('./seoHome')(query));
   router.use('/productHero', require('./productHero')(query));
   router.use('/cards', require('./cards')(query));
   router.use('/invitation', require('./invitation')(query));
   router.use('/characteristic', require('./characteristic')(query));
   router.use('/blogSection', require('./blogSection')(query));
   router.use('/contact-form', require('./contact-form')(query));
   router.use('/cart-form', require('./cart-form')(query));
   router.use('/adminProducts', require('./adminProducts')(query));
   router.use('/adminUsers', require('./adminUsers')(query));
   router.use('/products', require('./productGroup')(query));
   router.use('/views', require('./views')(query));
   router.use('/dashBoard', require('./dashBoard')(query));
   router.use('/dataPercent', require('./dataPercent')(query));
   router.use('/grapfic', require('./grapfic')(query));
   router.use('/products', require('./productsToggle')(query));
   router.use('/addProduct', require('./addProduct')(query));
   router.use('/delete', require('./delete')(query));
   router.use('/topProduct', require('./topProduct')(query));
   router.use('/cerf', require('./cerf')(query));
  router.use('/adminArticles', require('./adminArticles')(query));
 router.use('/adminPromotion', require('./adminPromotion')(query));
 router.use('/adminSeoBlocks', require('./adminSeoBlocks')(query));
  router.use('/articleSections', require('./articleSections')(query));
  router.use('/relatedArticles', require('./relatedArticles')(query));
  router.use('/articleCategories', require('./articleCategories')(query));
  router.use('/articleAuthors', require('./articleAuthors')(query));
  router.use('/auth', require('./auth')(query));
  router.use('/adminImages', require('./adminImages')(query));
  return router;
};